version: "3.8"
services:
  web:
    # Build from local.
    build: .
    # Build from remote GitHub branch.
    # image: ghcr.io/xxxxxx/yyyyyy/zzzzzz:latest
    restart: unless-stopped
    container_name: cpr-backend
    ports:
      - "80:9080"
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: cpr-mongo
    volumes:
      - ${DATABASE_FOLDER}:/db
      - ${INITIALIZE_SCRIPT}:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: cpr-nginx
    volumes:
      - ${NGINX}:/etc/nginx/conf.d/default.conf
